import { MdThumbUp, MdThumbDown } from "react-icons/md";
import { FaSteam, FaApple, FaWindows, FaXTwitter, FaFacebookF } from "react-icons/fa6";
import {
  LuX,
  LuUser,
  LuMenu,
  LuBell,
  LuHeart,
  LuUsers,
  LuCheck,
  LuLogOut,
  LuCircle,
  LuSearch,
  LuSettings,
  LuGamepad2,
  LuUserPlus,
  LuMailCheck,
  LuChevronUp,
  LuChevronLeft,
  LuChevronDown,
  LuShoppingCart,
  LuChevronRight,
  LuBadgeDollarSign,
} from "react-icons/lu";

export const Icons = {
  LuX,
  LuUser,
  LuMenu,
  LuBell,
  LuHeart,
  LuUsers,
  LuCheck,
  LuLogOut,
  LuCircle,
  LuSearch,
  LuSettings,
  LuGamepad2,
  LuUserPlus,
  LuMailCheck,
  LuChevronUp,
  LuChevronLeft,
  LuChevronDown,
  LuShoppingCart,
  LuChevronRight,
  LuBadgeDollarSign,
  // ================================== //
  MdThumbUp,
  MdThumbDown,
  // ================================== //
  FaSteam,
  FaApple,
  FaWindows,
  FaXTwitter,
  FaFacebookF,
};
