import { MdThumbDown, MdThumbUp } from "react-icons/md";
import {
  LuShoppingCart,
  LuHeart,
  LuSettings,
  LuSearch,
  LuChevronRight,
  LuChevronLeft,
  LuMailCheck,
  LuUser,
  LuGamepad2,
  LuBell,
  LuUsers,
  LuCheck,
  LuBadgeDollarSign,
  LuChevronDown,
  LuLogOut,
  LuUserPlus,
  LuChevronUp,
  LuCircle,
} from "react-icons/lu";
import { FaXTwitter, FaFacebookF, FaSteam, FaWindows, FaApple } from "react-icons/fa6";

export const Icons = {
  LuShoppingCart,
  LuHeart,
  LuSettings,
  LuSearch,
  LuUser,
  LuBell,
  LuUsers,
  LuGamepad2,
  LuMailCheck,
  LuLogOut,
  LuCircle,
  LuCheck,
  LuChevronRight,
  LuBadgeDollarSign,
  LuUserPlus,
  LuChevronDown,
  LuChevronUp,
  LuChevronLeft,
  // ================================== //
  MdThumbDown,
  MdThumbUp,
  // ================================== //
  FaSteam,
  FaWindows,
  FaApple,
  FaFacebookF,
  FaXTwitter,
};
